name: Run Dreamer
favicon: null
layout_spectrum: 1
typography_spectrum: 0.81132
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#565756'
    - '#00dbfb'
    - '#ff17f5'
  brandStrength: 0.375
  lightness: 0.9520528928842396
  saturation: 0.6930047031491995
  rhythmicContrast: 0.5
purpose: []
